version: '3'
services:
  chat-server:
    build: .
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=chat-db
      - SERVER_PORT=5000
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      - chat-server-network

  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    networks:
      - chat-server-network
 
networks:
  chat-server-network:
    external: false