enum fee_responsibility {
   PEMBELI_BELUM_MELAKUKAN_TRANSFER,
   PEMBELI_BERHASIL_TRANSFER,
   PENJUAL_TELAH_MENGIRIM_PRODUK,
   MENUNGGU_KONFIRMASI_SELESAI_PEMBELI,
   TRANSAKSI_TELAH_SELESAI,
}

export default fee_responsibility;
