###
POST https://app.sandbox.midtrans.com/snap/v1/transactions
Accept: application/json
Authorization: Basic SB-Mid-server-U3iTv_jdlhLtdHEjGjH28LEr
Content-Type: application/json

{
   "transaction_details": {
      "order_id": "1",
      "gross_amount": 2500000
   },
   "credit_card":{
        "secure" : true
    },
   "customer_details": {
      "first_name": "Kevin",
      "last_name": "ID",
      "email": "kevinid@example.com",
      "phone_number": "08111222333"
   }
}

### 
POST http://localhost:1337/api/v1/transaction/1/paymentship
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiS2V2aW4gSUQiLCJpYXQiOjE2ODQ0MzEyMDMsImV4cCI6MTY4NDQ4NTIwM30._vbS1MqkXEkuZejU-_ze36ljGzWCbuuH_-Rt-UxIE44
Content-Type: application/json
Accept: application/json

{
   "transaction_id": 3,
   "amount": 2500000,
   "username": "KevinID",
   "email": "kevin@test.com",
   "phone_number": "08512598321"
}